# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeebd429c1f601070dd2db8e89b3d587b80b16d4728b4d839e84eb792f1d5b4b0bb8e8767945710f8706f0598e1ad1b0ccbc2ad0e9bc1ff3aef783697210b321

test:
  secret_key_base: 3f1bc32ac0511acb3ab94dab33284355b0afba9696c6b00f0f7f824a1588675157de936213ee5baef7c47c5fbf067619c5c00006bc22670a12f8bfabeb3ca1ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
